// Anteater Electric Racing, 2025

#pragma once

#define DEBUG_FLAG 0

#define THREAD_MAIN_STACK_SIZE 128
#define THREAD_MAIN_PRIORITY 1
#define THREAD_MOTOR_STACK_SIZE 128
#define THREAD_MOTOR_PRIORITY 4
#define THREAD_CAN_TELEMETRY_STACK_SIZE 512
#define THREAD_CAN_TELEMETRY_PRIORITY 1
#define THREAD_ADC_STACK_SIZE 128
#define THREAD_ADC_PRIORITY 8

#define WHEEL_SPEED_1_PIN 2
#define WHEEL_SPEED_2_PIN 3
#define RTM_BUTTON_PIN 4

#define LOGIC_LEVEL_V 3.3F
#define TIME_STEP 0.001F // 1ms time step

#define ADC_AVERAGING 1
#define ADC_RESOLUTION 12
#define ADC_MAX_VALUE ((1 << ADC_RESOLUTION) - 1)
#define TICKTYPE_FREQUENCY 1

#define ADC_VOLTAGE_DIVIDER 2.0F
#define ADC_VALUE_TO_VOLTAGE(x) ((x) * (LOGIC_LEVEL_V / ADC_MAX_VALUE)) * ADC_VOLTAGE_DIVIDER

#define APPS_FAULT_PERCENT_MIN .1
#define APPS_FAULT_PERCENT_MAX .9

#define APPS1_VOLTAGE_LEVEL 3.3
#define APPS2_VOLTAGE_LEVEL 5

#define APPS_RANGE_MIN_PERCENT .15
#define APPS_RANGE_MAX_PERCENT .85

#define APPS_3V3_MIN (APPS1_VOLTAGE_LEVEL * APPS_RANGE_MIN_PERCENT)
#define APPS_3V3_MAX (APPS1_VOLTAGE_LEVEL * APPS_RANGE_MAX_PERCENT)

#define APPS_5V_MIN (APPS2_VOLTAGE_LEVEL * APPS_RANGE_MIN_PERCENT)
#define APPS_5V_MAX (APPS2_VOLTAGE_LEVEL * APPS_RANGE_MAX_PERCENT)

#define APPS_3V3_FAULT_MIN (APPS1_VOLTAGE_LEVEL * APPS_FAULT_PERCENT_MIN)
#define APPS_3V3_FAULT_MAX (APPS1_VOLTAGE_LEVEL * APPS_FAULT_PERCENT_MAX)

#define APPS_5V_FAULT_MIN (APPS2_VOLTAGE_LEVEL * APPS_FAULT_PERCENT_MIN)
#define APPS_5V_FAULT_MAX (APPS2_VOLTAGE_LEVEL * APPS_FAULT_PERCENT_MAX)

#define APPS_FAULT_TIME_THRESHOLD_MS 100

#define APPS_IMPLAUSABILITY_THRESHOLD 0.1            // 10%
#define APPS_BSE_PLAUSABILITY_TROTTLE_THRESHOLD 0.25 // 25%
#define APPS_BSE_PLAUSABILITY_BRAKE_THRESHOLD 1.5 // TODO: change back to PSI200    // PSI
#define APPS_BSE_PLAUSIBILITY_RESET_THRESHOLD 0.05 // 5%

#define BSE_VOLTAGE_DIVIDER 2.0F // TODO: Update with real value
#define BSE_ADC_VALUE_TO_VOLTAGE(x) (x * (LOGIC_LEVEL_V / ADC_MAX_VALUE)) * BSE_VOLTAGE_DIVIDER // ADC value to voltage conversion

#define BSE_VOLTAGE_TO_PSI(x) x // Voltage to PSI conversion

#define BSE_LOWER_THRESHOLD 0.5F
#define BSE_UPPER_THRESHOLD 4.5F
#define BSE_IMPLAUSABILITY_THRESHOLD 0.1F

#define BSE_FAULT_TIME_THRESHOLD_MS 100

#define BSE_CUTOFF_HZ 100.0F

#define MOTOR_MAX_TORQUE 260.0F // TODO: Update with real value

#define BATTERY_MAX_CURRENT_A 1.0F
#define BATTERY_MAX_REGEN_A 1.0F

#define COMPUTE_ALPHA(CUTOFF_HZ) \
    (1.0F / (1.0F + (1.0F / (2.0F * M_PI * CUTOFF_HZ)) / TIME_STEP))

#define LOWPASS_FILTER(NEW, OLD, ALPHA) \
    OLD = ALPHA * NEW + (1.0F - ALPHA) * OLD

#define LINEAR_MAP(x, in_min, in_max, out_min, out_max) \
    ((x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min)

#define CHANGE_ENDIANESS_16(x) \
    (((x & 0xFF00) >> 8) | ((x & 0x00FF) << 8))

#define MOTOR_DIRECTION_STANDBY 0
#define MOTOR_DIRECTION_FORWARD 1
#define MOTOR_DIRECTION_BACKWARD 2
#define MOTOR_DIRECTION_ERROR 3

#define MAX_REGEN_TORQUE -9.0F // TODO: test with higher value regen
#define REGEN_BIAS 1 // Scale 0-1 of max regen torque
