#!/bin/sh
### BEGIN INIT INFO
# Provides:          influxdb3
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: InfluxDB3 service
### END INIT INFO

DAEMON="/home/vscode/.influxdb/influxdb3"
DAEMON_ARGS="serve --object-store file --data-dir ~/.influxdb3 --node-id my-host-01 --admin-token-file /workspaces/embedded/.devcontainer/admin-token.json"
PIDFILE="/var/run/influxdb3.pid"
LOGFILE="/var/log/influxdb3.log"
LOCKFILE="/var/lock/influxdb3"

restart_daemon() {
    while [ -f "$LOCKFILE" ]; do
        echo "$(date): Starting influxdb3..." >> $LOGFILE
        $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1
        if [ -f "$LOCKFILE" ]; then
            echo "$(date): influxdb3 exited unexpectedly, restarting in 5 seconds..." >> $LOGFILE
            sleep 5
        fi
    done
}

case "$1" in
  start)
    echo "Starting influxdb3..."
    if [ -f "$PIDFILE" ]; then
        echo "influxdb3 is already running (PID file exists)"
        exit 1
    fi
    touch $LOCKFILE
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background \
      --startas /bin/sh -- -c "restart_daemon() { while [ -f '$LOCKFILE' ]; do echo \"\$(date): Starting influxdb3...\" >> $LOGFILE; $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1; if [ -f '$LOCKFILE' ]; then echo \"\$(date): influxdb3 exited unexpectedly, restarting in 5 seconds...\" >> $LOGFILE; sleep 5; fi; done; }; restart_daemon"
    ;;
  stop)
    echo "Stopping influxdb3..."
    rm -f $LOCKFILE
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    rm -f $PIDFILE
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  status)
    if [ -f "$PIDFILE" ]; then
        echo "influxdb3 is running (PID $(cat $PIDFILE))"
    else
        echo "influxdb3 is not running"
    fi
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0